package com.android.forge.contacts2.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.RawContacts;

/**
 * Class _Accounts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Accounts extends CayenneDataObject {

    public static final String TO_RAW_CONTACTS_PROPERTY = "toRawContacts";


    public void addToToRawContacts(RawContacts obj) {
        addToManyTarget("toRawContacts", obj, true);
    }
    public void removeFromToRawContacts(RawContacts obj) {
        removeToManyTarget("toRawContacts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RawContacts> getToRawContacts() {
        return (List<RawContacts>)readProperty("toRawContacts");
    }


}
