package com.android.forge.contacts2.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Calls was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Calls extends CayenneDataObject {

    public static final String CITY_ID_PROPERTY = "cityId";
    public static final String CS_LOCAL_UUID_PROPERTY = "csLocalUuid";
    public static final String CS_TIMESTAMP_PROPERTY = "csTimestamp";
    public static final String DATE_PROPERTY = "date";
    public static final String DURATION_PROPERTY = "duration";
    public static final String NAME_PROPERTY = "name";
    public static final String NEW_PROPERTY = "new";
    public static final String NUMBER_PROPERTY = "number";
    public static final String NUMBERLABEL_PROPERTY = "numberlabel";
    public static final String NUMBERTYPE_PROPERTY = "numbertype";
    public static final String RAW_CONTACT_ID_PROPERTY = "rawContactId";
    public static final String TYPE_PROPERTY = "type";

    public static final String _ID_PK_COLUMN = "_id";

    public void setCityId(String cityId) {
        writeProperty("cityId", cityId);
    }
    public String getCityId() {
        return (String)readProperty("cityId");
    }

    public void setCsLocalUuid(String csLocalUuid) {
        writeProperty("csLocalUuid", csLocalUuid);
    }
    public String getCsLocalUuid() {
        return (String)readProperty("csLocalUuid");
    }

    public void setCsTimestamp(Integer csTimestamp) {
        writeProperty("csTimestamp", csTimestamp);
    }
    public Integer getCsTimestamp() {
        return (Integer)readProperty("csTimestamp");
    }

    public void setDate(Long date) {
        writeProperty("date", date);
    }
    public Long getDate() {
        return (Long)readProperty("date");
    }

    public void setDuration(Integer duration) {
        writeProperty("duration", duration);
    }
    public Integer getDuration() {
        return (Integer)readProperty("duration");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNew(Integer _new) {
        writeProperty("new", _new);
    }
    public Integer getNew() {
        return (Integer)readProperty("new");
    }

    public void setNumber(String number) {
        writeProperty("number", number);
    }
    public String getNumber() {
        return (String)readProperty("number");
    }

    public void setNumberlabel(String numberlabel) {
        writeProperty("numberlabel", numberlabel);
    }
    public String getNumberlabel() {
        return (String)readProperty("numberlabel");
    }

    public void setNumbertype(Integer numbertype) {
        writeProperty("numbertype", numbertype);
    }
    public Integer getNumbertype() {
        return (Integer)readProperty("numbertype");
    }

    public void setRawContactId(Integer rawContactId) {
        writeProperty("rawContactId", rawContactId);
    }
    public Integer getRawContactId() {
        return (Integer)readProperty("rawContactId");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

}
