package com.android.forge.contacts2.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.RawContacts;

/**
 * Class _Contacts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contacts extends CayenneDataObject {

    public static final String CUSTOM_RINGTONE_PROPERTY = "customRingtone";
    public static final String DEFAULT_ACTION_PROPERTY = "defaultAction";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String EXT_ACCOUNT_TYPE_PROPERTY = "extAccountType";
    public static final String EXT_PHOTO_URL_PROPERTY = "extPhotoUrl";
    public static final String HAS_PHONE_NUMBER_PROPERTY = "hasPhoneNumber";
    public static final String IN_VISIBLE_GROUP_PROPERTY = "inVisibleGroup";
    public static final String LAST_TIME_CONTACTED_PROPERTY = "lastTimeContacted";
    public static final String LOOKUP_PROPERTY = "lookup";
    public static final String PHOTO_ID_PROPERTY = "photoId";
    public static final String SEND_TO_VOICEMAIL_PROPERTY = "sendToVoicemail";
    public static final String SINGLE_IS_RESTRICTED_PROPERTY = "singleIsRestricted";
    public static final String STARRED_PROPERTY = "starred";
    public static final String STATUS_UPDATE_ID_PROPERTY = "statusUpdateId";
    public static final String TIMES_CONTACTED_PROPERTY = "timesContacted";
    public static final String VIP_PROPERTY = "vip";
    public static final String RAW_CONTACT_PROPERTY = "rawContact";

    public static final String _ID_PK_COLUMN = "_id";

    public void setCustomRingtone(String customRingtone) {
        writeProperty("customRingtone", customRingtone);
    }
    public String getCustomRingtone() {
        return (String)readProperty("customRingtone");
    }

    public void setDefaultAction(String defaultAction) {
        writeProperty("defaultAction", defaultAction);
    }
    public String getDefaultAction() {
        return (String)readProperty("defaultAction");
    }

    public void setDisplayName(String displayName) {
        writeProperty("displayName", displayName);
    }
    public String getDisplayName() {
        return (String)readProperty("displayName");
    }

    public void setExtAccountType(String extAccountType) {
        writeProperty("extAccountType", extAccountType);
    }
    public String getExtAccountType() {
        return (String)readProperty("extAccountType");
    }

    public void setExtPhotoUrl(String extPhotoUrl) {
        writeProperty("extPhotoUrl", extPhotoUrl);
    }
    public String getExtPhotoUrl() {
        return (String)readProperty("extPhotoUrl");
    }

    public void setHasPhoneNumber(Integer hasPhoneNumber) {
        writeProperty("hasPhoneNumber", hasPhoneNumber);
    }
    public Integer getHasPhoneNumber() {
        return (Integer)readProperty("hasPhoneNumber");
    }

    public void setInVisibleGroup(Integer inVisibleGroup) {
        writeProperty("inVisibleGroup", inVisibleGroup);
    }
    public Integer getInVisibleGroup() {
        return (Integer)readProperty("inVisibleGroup");
    }

    public void setLastTimeContacted(Integer lastTimeContacted) {
        writeProperty("lastTimeContacted", lastTimeContacted);
    }
    public Integer getLastTimeContacted() {
        return (Integer)readProperty("lastTimeContacted");
    }

    public void setLookup(String lookup) {
        writeProperty("lookup", lookup);
    }
    public String getLookup() {
        return (String)readProperty("lookup");
    }

    public void setPhotoId(Integer photoId) {
        writeProperty("photoId", photoId);
    }
    public Integer getPhotoId() {
        return (Integer)readProperty("photoId");
    }

    public void setSendToVoicemail(Integer sendToVoicemail) {
        writeProperty("sendToVoicemail", sendToVoicemail);
    }
    public Integer getSendToVoicemail() {
        return (Integer)readProperty("sendToVoicemail");
    }

    public void setSingleIsRestricted(Integer singleIsRestricted) {
        writeProperty("singleIsRestricted", singleIsRestricted);
    }
    public Integer getSingleIsRestricted() {
        return (Integer)readProperty("singleIsRestricted");
    }

    public void setStarred(Integer starred) {
        writeProperty("starred", starred);
    }
    public Integer getStarred() {
        return (Integer)readProperty("starred");
    }

    public void setStatusUpdateId(Integer statusUpdateId) {
        writeProperty("statusUpdateId", statusUpdateId);
    }
    public Integer getStatusUpdateId() {
        return (Integer)readProperty("statusUpdateId");
    }

    public void setTimesContacted(Integer timesContacted) {
        writeProperty("timesContacted", timesContacted);
    }
    public Integer getTimesContacted() {
        return (Integer)readProperty("timesContacted");
    }

    public void setVip(Integer vip) {
        writeProperty("vip", vip);
    }
    public Integer getVip() {
        return (Integer)readProperty("vip");
    }

    public void setRawContact(RawContacts rawContact) {
        setToOneTarget("rawContact", rawContact, true);
    }

    public RawContacts getRawContact() {
        return (RawContacts)readProperty("rawContact");
    }


}
