package com.android.forge.contacts2.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.Mimetypes;
import com.android.forge.contacts2.Packages;
import com.android.forge.contacts2.PhoneLookup;
import com.android.forge.contacts2.RawContacts;

/**
 * Class _Data was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Data extends CayenneDataObject {

    public static final String DATA1_PROPERTY = "data1";
    public static final String DATA10_PROPERTY = "data10";
    public static final String DATA11_PROPERTY = "data11";
    public static final String DATA12_PROPERTY = "data12";
    public static final String DATA13_PROPERTY = "data13";
    public static final String DATA14_PROPERTY = "data14";
    public static final String DATA15_PROPERTY = "data15";
    public static final String DATA2_PROPERTY = "data2";
    public static final String DATA3_PROPERTY = "data3";
    public static final String DATA4_PROPERTY = "data4";
    public static final String DATA5_PROPERTY = "data5";
    public static final String DATA6_PROPERTY = "data6";
    public static final String DATA7_PROPERTY = "data7";
    public static final String DATA8_PROPERTY = "data8";
    public static final String DATA9_PROPERTY = "data9";
    public static final String DATA_SYNC1_PROPERTY = "dataSync1";
    public static final String DATA_SYNC2_PROPERTY = "dataSync2";
    public static final String DATA_SYNC3_PROPERTY = "dataSync3";
    public static final String DATA_SYNC4_PROPERTY = "dataSync4";
    public static final String DATA_VERSION_PROPERTY = "dataVersion";
    public static final String IS_PRIMARY_PROPERTY = "isPrimary";
    public static final String IS_SUPER_PRIMARY_PROPERTY = "isSuperPrimary";
    public static final String MIMETYPE_PROPERTY = "Mimetype";
    public static final String PACKAGE_PROPERTY = "Package";
    public static final String PHONE_LOOKUP_PROPERTY = "PhoneLookup";
    public static final String RAW_CONTACTS_PROPERTY = "rawContacts";

    public static final String _ID_PK_COLUMN = "_id";

    public void setData1(String data1) {
        writeProperty("data1", data1);
    }
    public String getData1() {
        return (String)readProperty("data1");
    }

    public void setData10(String data10) {
        writeProperty("data10", data10);
    }
    public String getData10() {
        return (String)readProperty("data10");
    }

    public void setData11(String data11) {
        writeProperty("data11", data11);
    }
    public String getData11() {
        return (String)readProperty("data11");
    }

    public void setData12(String data12) {
        writeProperty("data12", data12);
    }
    public String getData12() {
        return (String)readProperty("data12");
    }

    public void setData13(String data13) {
        writeProperty("data13", data13);
    }
    public String getData13() {
        return (String)readProperty("data13");
    }

    public void setData14(String data14) {
        writeProperty("data14", data14);
    }
    public String getData14() {
        return (String)readProperty("data14");
    }

    public void setData15(String data15) {
        writeProperty("data15", data15);
    }
    public String getData15() {
        return (String)readProperty("data15");
    }

    public void setData2(String data2) {
        writeProperty("data2", data2);
    }
    public String getData2() {
        return (String)readProperty("data2");
    }

    public void setData3(String data3) {
        writeProperty("data3", data3);
    }
    public String getData3() {
        return (String)readProperty("data3");
    }

    public void setData4(String data4) {
        writeProperty("data4", data4);
    }
    public String getData4() {
        return (String)readProperty("data4");
    }

    public void setData5(String data5) {
        writeProperty("data5", data5);
    }
    public String getData5() {
        return (String)readProperty("data5");
    }

    public void setData6(String data6) {
        writeProperty("data6", data6);
    }
    public String getData6() {
        return (String)readProperty("data6");
    }

    public void setData7(String data7) {
        writeProperty("data7", data7);
    }
    public String getData7() {
        return (String)readProperty("data7");
    }

    public void setData8(String data8) {
        writeProperty("data8", data8);
    }
    public String getData8() {
        return (String)readProperty("data8");
    }

    public void setData9(String data9) {
        writeProperty("data9", data9);
    }
    public String getData9() {
        return (String)readProperty("data9");
    }

    public void setDataSync1(String dataSync1) {
        writeProperty("dataSync1", dataSync1);
    }
    public String getDataSync1() {
        return (String)readProperty("dataSync1");
    }

    public void setDataSync2(String dataSync2) {
        writeProperty("dataSync2", dataSync2);
    }
    public String getDataSync2() {
        return (String)readProperty("dataSync2");
    }

    public void setDataSync3(String dataSync3) {
        writeProperty("dataSync3", dataSync3);
    }
    public String getDataSync3() {
        return (String)readProperty("dataSync3");
    }

    public void setDataSync4(String dataSync4) {
        writeProperty("dataSync4", dataSync4);
    }
    public String getDataSync4() {
        return (String)readProperty("dataSync4");
    }

    public void setDataVersion(Integer dataVersion) {
        writeProperty("dataVersion", dataVersion);
    }
    public Integer getDataVersion() {
        return (Integer)readProperty("dataVersion");
    }

    public void setIsPrimary(Integer isPrimary) {
        writeProperty("isPrimary", isPrimary);
    }
    public Integer getIsPrimary() {
        return (Integer)readProperty("isPrimary");
    }

    public void setIsSuperPrimary(Integer isSuperPrimary) {
        writeProperty("isSuperPrimary", isSuperPrimary);
    }
    public Integer getIsSuperPrimary() {
        return (Integer)readProperty("isSuperPrimary");
    }

    public void setMimetype(Mimetypes Mimetype) {
        setToOneTarget("Mimetype", Mimetype, true);
    }

    public Mimetypes getMimetype() {
        return (Mimetypes)readProperty("Mimetype");
    }


    public void setPackage(Packages Package) {
        setToOneTarget("Package", Package, true);
    }

    public Packages getPackage() {
        return (Packages)readProperty("Package");
    }


    public void addToPhoneLookup(PhoneLookup obj) {
        addToManyTarget("PhoneLookup", obj, true);
    }
    public void removeFromPhoneLookup(PhoneLookup obj) {
        removeToManyTarget("PhoneLookup", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PhoneLookup> getPhoneLookup() {
        return (List<PhoneLookup>)readProperty("PhoneLookup");
    }


    public void setRawContacts(RawContacts rawContacts) {
        setToOneTarget("rawContacts", rawContacts, true);
    }

    public RawContacts getRawContacts() {
        return (RawContacts)readProperty("rawContacts");
    }


}
