package com.android.forge.contacts2.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.Data;

/**
 * Class _Mimetypes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Mimetypes extends CayenneDataObject {

    public static final String MIMETYPE_PROPERTY = "mimetype";
    public static final String DATA_PROPERTY = "Data";

    public static final String _ID_PK_COLUMN = "_id";

    public void setMimetype(String mimetype) {
        writeProperty("mimetype", mimetype);
    }
    public String getMimetype() {
        return (String)readProperty("mimetype");
    }

    public void addToData(Data obj) {
        addToManyTarget("Data", obj, true);
    }
    public void removeFromData(Data obj) {
        removeToManyTarget("Data", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Data> getData() {
        return (List<Data>)readProperty("Data");
    }


}
