package com.android.forge.contacts2.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.Data;

/**
 * Class _Packages was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Packages extends CayenneDataObject {

    public static final String PACKAGE_PROPERTY = "package";
    public static final String DATA_PROPERTY = "Data";

    public static final String _ID_PK_COLUMN = "_id";

    public void setPackage(String _package) {
        writeProperty("package", _package);
    }
    public String getPackage() {
        return (String)readProperty("package");
    }

    public void addToData(Data obj) {
        addToManyTarget("Data", obj, true);
    }
    public void removeFromData(Data obj) {
        removeToManyTarget("Data", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Data> getData() {
        return (List<Data>)readProperty("Data");
    }


}
