package com.android.forge.contacts2.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.Data;
import com.android.forge.contacts2.RawContacts;

/**
 * Class _PhoneLookup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PhoneLookup extends CayenneDataObject {

    public static final String MIN_MATCH_PROPERTY = "minMatch";
    public static final String NORMALIZED_NUMBER_PROPERTY = "normalizedNumber";
    public static final String DATA_PROPERTY = "Data";
    public static final String RAW_CONTACT_PROPERTY = "rawContact";

    public static final String DATA_ID_PK_COLUMN = "data_id";

    public void setMinMatch(String minMatch) {
        writeProperty("minMatch", minMatch);
    }
    public String getMinMatch() {
        return (String)readProperty("minMatch");
    }

    public void setNormalizedNumber(String normalizedNumber) {
        writeProperty("normalizedNumber", normalizedNumber);
    }
    public String getNormalizedNumber() {
        return (String)readProperty("normalizedNumber");
    }

    public void setData(Data Data) {
        setToOneTarget("Data", Data, true);
    }

    public Data getData() {
        return (Data)readProperty("Data");
    }


    public void setRawContact(RawContacts rawContact) {
        setToOneTarget("rawContact", rawContact, true);
    }

    public RawContacts getRawContact() {
        return (RawContacts)readProperty("rawContact");
    }


}
