package com.android.forge.contacts2.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.contacts2.Contacts;
import com.android.forge.contacts2.Data;
import com.android.forge.contacts2.PhoneLookup;

/**
 * Class _RawContacts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RawContacts extends CayenneDataObject {

    public static final String ACCOUNT_NAME_PROPERTY = "accountName";
    public static final String ACCOUNT_TYPE_PROPERTY = "accountType";
    public static final String AGGREGATION_MODE_PROPERTY = "aggregationMode";
    public static final String AGGREGATION_NEEDED_PROPERTY = "aggregationNeeded";
    public static final String CONTACT_IN_VISIBLE_GROUP_PROPERTY = "contactInVisibleGroup";
    public static final String CUSTOM_RINGTONE_PROPERTY = "customRingtone";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String DIRTY_PROPERTY = "dirty";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String DISPLAY_NAME_ALT_PROPERTY = "displayNameAlt";
    public static final String DISPLAY_NAME_SOURCE_PROPERTY = "displayNameSource";
    public static final String IS_RESTRICTED_PROPERTY = "isRestricted";
    public static final String LAST_TIME_CONTACTED_PROPERTY = "lastTimeContacted";
    public static final String NAME_VERIFIED_PROPERTY = "nameVerified";
    public static final String PHONETIC_NAME_PROPERTY = "phoneticName";
    public static final String PHONETIC_NAME_STYLE_PROPERTY = "phoneticNameStyle";
    public static final String SEND_TO_VOICEMAIL_PROPERTY = "sendToVoicemail";
    public static final String SORT_KEY_PROPERTY = "sortKey";
    public static final String SORT_KEY_ALT_PROPERTY = "sortKeyAlt";
    public static final String SOURCEID_PROPERTY = "sourceid";
    public static final String STARRED_PROPERTY = "starred";
    public static final String SYNC1_PROPERTY = "sync1";
    public static final String SYNC2_PROPERTY = "sync2";
    public static final String SYNC3_PROPERTY = "sync3";
    public static final String SYNC4_PROPERTY = "sync4";
    public static final String TIMES_CONTACTED_PROPERTY = "timesContacted";
    public static final String VERSION_PROPERTY = "version";
    public static final String VIP_PROPERTY = "vip";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String DATA_PROPERTY = "data";
    public static final String PHONE_LOOKUP_PROPERTY = "phoneLookup";

    public static final String _ID_PK_COLUMN = "_id";

    public void setAccountName(String accountName) {
        writeProperty("accountName", accountName);
    }
    public String getAccountName() {
        return (String)readProperty("accountName");
    }

    public void setAccountType(String accountType) {
        writeProperty("accountType", accountType);
    }
    public String getAccountType() {
        return (String)readProperty("accountType");
    }

    public void setAggregationMode(Integer aggregationMode) {
        writeProperty("aggregationMode", aggregationMode);
    }
    public Integer getAggregationMode() {
        return (Integer)readProperty("aggregationMode");
    }

    public void setAggregationNeeded(Integer aggregationNeeded) {
        writeProperty("aggregationNeeded", aggregationNeeded);
    }
    public Integer getAggregationNeeded() {
        return (Integer)readProperty("aggregationNeeded");
    }

    public void setContactInVisibleGroup(Integer contactInVisibleGroup) {
        writeProperty("contactInVisibleGroup", contactInVisibleGroup);
    }
    public Integer getContactInVisibleGroup() {
        return (Integer)readProperty("contactInVisibleGroup");
    }

    public void setCustomRingtone(String customRingtone) {
        writeProperty("customRingtone", customRingtone);
    }
    public String getCustomRingtone() {
        return (String)readProperty("customRingtone");
    }

    public void setDeleted(Integer deleted) {
        writeProperty("deleted", deleted);
    }
    public Integer getDeleted() {
        return (Integer)readProperty("deleted");
    }

    public void setDirty(Integer dirty) {
        writeProperty("dirty", dirty);
    }
    public Integer getDirty() {
        return (Integer)readProperty("dirty");
    }

    public void setDisplayName(String displayName) {
        writeProperty("displayName", displayName);
    }
    public String getDisplayName() {
        return (String)readProperty("displayName");
    }

    public void setDisplayNameAlt(String displayNameAlt) {
        writeProperty("displayNameAlt", displayNameAlt);
    }
    public String getDisplayNameAlt() {
        return (String)readProperty("displayNameAlt");
    }

    public void setDisplayNameSource(Integer displayNameSource) {
        writeProperty("displayNameSource", displayNameSource);
    }
    public Integer getDisplayNameSource() {
        return (Integer)readProperty("displayNameSource");
    }

    public void setIsRestricted(Integer isRestricted) {
        writeProperty("isRestricted", isRestricted);
    }
    public Integer getIsRestricted() {
        return (Integer)readProperty("isRestricted");
    }

    public void setLastTimeContacted(Integer lastTimeContacted) {
        writeProperty("lastTimeContacted", lastTimeContacted);
    }
    public Integer getLastTimeContacted() {
        return (Integer)readProperty("lastTimeContacted");
    }

    public void setNameVerified(Integer nameVerified) {
        writeProperty("nameVerified", nameVerified);
    }
    public Integer getNameVerified() {
        return (Integer)readProperty("nameVerified");
    }

    public void setPhoneticName(String phoneticName) {
        writeProperty("phoneticName", phoneticName);
    }
    public String getPhoneticName() {
        return (String)readProperty("phoneticName");
    }

    public void setPhoneticNameStyle(String phoneticNameStyle) {
        writeProperty("phoneticNameStyle", phoneticNameStyle);
    }
    public String getPhoneticNameStyle() {
        return (String)readProperty("phoneticNameStyle");
    }

    public void setSendToVoicemail(Integer sendToVoicemail) {
        writeProperty("sendToVoicemail", sendToVoicemail);
    }
    public Integer getSendToVoicemail() {
        return (Integer)readProperty("sendToVoicemail");
    }

    public void setSortKey(String sortKey) {
        writeProperty("sortKey", sortKey);
    }
    public String getSortKey() {
        return (String)readProperty("sortKey");
    }

    public void setSortKeyAlt(String sortKeyAlt) {
        writeProperty("sortKeyAlt", sortKeyAlt);
    }
    public String getSortKeyAlt() {
        return (String)readProperty("sortKeyAlt");
    }

    public void setSourceid(String sourceid) {
        writeProperty("sourceid", sourceid);
    }
    public String getSourceid() {
        return (String)readProperty("sourceid");
    }

    public void setStarred(Integer starred) {
        writeProperty("starred", starred);
    }
    public Integer getStarred() {
        return (Integer)readProperty("starred");
    }

    public void setSync1(String sync1) {
        writeProperty("sync1", sync1);
    }
    public String getSync1() {
        return (String)readProperty("sync1");
    }

    public void setSync2(String sync2) {
        writeProperty("sync2", sync2);
    }
    public String getSync2() {
        return (String)readProperty("sync2");
    }

    public void setSync3(String sync3) {
        writeProperty("sync3", sync3);
    }
    public String getSync3() {
        return (String)readProperty("sync3");
    }

    public void setSync4(String sync4) {
        writeProperty("sync4", sync4);
    }
    public String getSync4() {
        return (String)readProperty("sync4");
    }

    public void setTimesContacted(Integer timesContacted) {
        writeProperty("timesContacted", timesContacted);
    }
    public Integer getTimesContacted() {
        return (Integer)readProperty("timesContacted");
    }

    public void setVersion(Integer version) {
        writeProperty("version", version);
    }
    public Integer getVersion() {
        return (Integer)readProperty("version");
    }

    public void setVip(Integer vip) {
        writeProperty("vip", vip);
    }
    public Integer getVip() {
        return (Integer)readProperty("vip");
    }

    public void setContact(Contacts contact) {
        setToOneTarget("contact", contact, true);
    }

    public Contacts getContact() {
        return (Contacts)readProperty("contact");
    }


    public void addToData(Data obj) {
        addToManyTarget("data", obj, true);
    }
    public void removeFromData(Data obj) {
        removeToManyTarget("data", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Data> getData() {
        return (List<Data>)readProperty("data");
    }


    public void addToPhoneLookup(PhoneLookup obj) {
        addToManyTarget("phoneLookup", obj, true);
    }
    public void removeFromPhoneLookup(PhoneLookup obj) {
        removeToManyTarget("phoneLookup", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PhoneLookup> getPhoneLookup() {
        return (List<PhoneLookup>)readProperty("phoneLookup");
    }


}
