package com.android.forge.calendar.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _CalendarSmsAlerts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarSmsAlerts extends CayenneDataObject {

    public static final String ALARM_TIME_PROPERTY = "alarmTime";
    public static final String BEGIN_PROPERTY = "begin";
    public static final String CREATION_TIME_PROPERTY = "creationTime";
    public static final String END_PROPERTY = "end";
    public static final String MINUTES_PROPERTY = "minutes";
    public static final String NOTIFY_TIME_PROPERTY = "notifyTime";
    public static final String RECEIVED_TIME_PROPERTY = "receivedTime";
    public static final String STATE_PROPERTY = "state";
    public static final String TO_EVENTS_PROPERTY = "toEvents";

    public static final String _ID_PK_COLUMN = "_id";

    public void setAlarmTime(Integer alarmTime) {
        writeProperty("alarmTime", alarmTime);
    }
    public Integer getAlarmTime() {
        return (Integer)readProperty("alarmTime");
    }

    public void setBegin(Integer begin) {
        writeProperty("begin", begin);
    }
    public Integer getBegin() {
        return (Integer)readProperty("begin");
    }

    public void setCreationTime(Integer creationTime) {
        writeProperty("creationTime", creationTime);
    }
    public Integer getCreationTime() {
        return (Integer)readProperty("creationTime");
    }

    public void setEnd(Integer end) {
        writeProperty("end", end);
    }
    public Integer getEnd() {
        return (Integer)readProperty("end");
    }

    public void setMinutes(Integer minutes) {
        writeProperty("minutes", minutes);
    }
    public Integer getMinutes() {
        return (Integer)readProperty("minutes");
    }

    public void setNotifyTime(Integer notifyTime) {
        writeProperty("notifyTime", notifyTime);
    }
    public Integer getNotifyTime() {
        return (Integer)readProperty("notifyTime");
    }

    public void setReceivedTime(Integer receivedTime) {
        writeProperty("receivedTime", receivedTime);
    }
    public Integer getReceivedTime() {
        return (Integer)readProperty("receivedTime");
    }

    public void setState(Integer state) {
        writeProperty("state", state);
    }
    public Integer getState() {
        return (Integer)readProperty("state");
    }

    public void setToEvents(Events toEvents) {
        setToOneTarget("toEvents", toEvents, true);
    }

    public Events getToEvents() {
        return (Events)readProperty("toEvents");
    }


}
