package com.android.forge.calendar.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _Calendars was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Calendars extends CayenneDataObject {

    public static final String ACCESS_LEVEL_PROPERTY = "accessLevel";
    public static final String ALERTS_RINGTONE_PROPERTY = "alertsRingtone";
    public static final String ALERTS_VIBRATE_PROPERTY = "alertsVibrate";
    public static final String COLOR_PROPERTY = "color";
    public static final String DETAILED_VIEW_PROPERTY = "detailedView";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String DISPLAY_ORDER_PROPERTY = "displayOrder";
    public static final String HIDDEN_PROPERTY = "hidden";
    public static final String HIDE_DECLINED_PROPERTY = "hideDeclined";
    public static final String LOCATION_PROPERTY = "location";
    public static final String NAME_PROPERTY = "name";
    public static final String ORGANIZER_CAN_RESPOND_PROPERTY = "organizerCanRespond";
    public static final String OWNER_ACCOUNT_PROPERTY = "ownerAccount";
    public static final String REMINDER_DURATION_PROPERTY = "reminderDuration";
    public static final String REMINDER_TYPE_PROPERTY = "reminderType";
    public static final String SELECTED_PROPERTY = "selected";
    public static final String START_VIEW_PROPERTY = "startView";
    public static final String SYNC_ACCOUNT_PROPERTY = "syncAccount";
    public static final String SYNC_ACCOUNT_TYPE_PROPERTY = "syncAccountType";
    public static final String SYNC_DIRTY_PROPERTY = "syncDirty";
    public static final String SYNC_EVENTS_PROPERTY = "syncEvents";
    public static final String SYNC_ID_PROPERTY = "syncId";
    public static final String SYNC_LOCAL_ID_PROPERTY = "syncLocalId";
    public static final String SYNC_MARK_PROPERTY = "syncMark";
    public static final String SYNC_SOURCE_PROPERTY = "syncSource";
    public static final String SYNC_TIME_PROPERTY = "syncTime";
    public static final String SYNC_VERSION_PROPERTY = "syncVersion";
    public static final String TIMEZONE_PROPERTY = "timezone";
    public static final String URL_PROPERTY = "url";
    public static final String UNTITLED_REL_PROPERTY = "untitledRel";

    public static final String _ID_PK_COLUMN = "_id";

    public void setAccessLevel(Integer accessLevel) {
        writeProperty("accessLevel", accessLevel);
    }
    public Integer getAccessLevel() {
        return (Integer)readProperty("accessLevel");
    }

    public void setAlertsRingtone(String alertsRingtone) {
        writeProperty("alertsRingtone", alertsRingtone);
    }
    public String getAlertsRingtone() {
        return (String)readProperty("alertsRingtone");
    }

    public void setAlertsVibrate(Integer alertsVibrate) {
        writeProperty("alertsVibrate", alertsVibrate);
    }
    public Integer getAlertsVibrate() {
        return (Integer)readProperty("alertsVibrate");
    }

    public void setColor(Integer color) {
        writeProperty("color", color);
    }
    public Integer getColor() {
        return (Integer)readProperty("color");
    }

    public void setDetailedView(String detailedView) {
        writeProperty("detailedView", detailedView);
    }
    public String getDetailedView() {
        return (String)readProperty("detailedView");
    }

    public void setDisplayName(String displayName) {
        writeProperty("displayName", displayName);
    }
    public String getDisplayName() {
        return (String)readProperty("displayName");
    }

    public void setDisplayOrder(Integer displayOrder) {
        writeProperty("displayOrder", displayOrder);
    }
    public Integer getDisplayOrder() {
        return (Integer)readProperty("displayOrder");
    }

    public void setHidden(Integer hidden) {
        writeProperty("hidden", hidden);
    }
    public Integer getHidden() {
        return (Integer)readProperty("hidden");
    }

    public void setHideDeclined(Integer hideDeclined) {
        writeProperty("hideDeclined", hideDeclined);
    }
    public Integer getHideDeclined() {
        return (Integer)readProperty("hideDeclined");
    }

    public void setLocation(String location) {
        writeProperty("location", location);
    }
    public String getLocation() {
        return (String)readProperty("location");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setOrganizerCanRespond(Integer organizerCanRespond) {
        writeProperty("organizerCanRespond", organizerCanRespond);
    }
    public Integer getOrganizerCanRespond() {
        return (Integer)readProperty("organizerCanRespond");
    }

    public void setOwnerAccount(String ownerAccount) {
        writeProperty("ownerAccount", ownerAccount);
    }
    public String getOwnerAccount() {
        return (String)readProperty("ownerAccount");
    }

    public void setReminderDuration(Integer reminderDuration) {
        writeProperty("reminderDuration", reminderDuration);
    }
    public Integer getReminderDuration() {
        return (Integer)readProperty("reminderDuration");
    }

    public void setReminderType(Integer reminderType) {
        writeProperty("reminderType", reminderType);
    }
    public Integer getReminderType() {
        return (Integer)readProperty("reminderType");
    }

    public void setSelected(Integer selected) {
        writeProperty("selected", selected);
    }
    public Integer getSelected() {
        return (Integer)readProperty("selected");
    }

    public void setStartView(String startView) {
        writeProperty("startView", startView);
    }
    public String getStartView() {
        return (String)readProperty("startView");
    }

    public void setSyncAccount(String syncAccount) {
        writeProperty("syncAccount", syncAccount);
    }
    public String getSyncAccount() {
        return (String)readProperty("syncAccount");
    }

    public void setSyncAccountType(String syncAccountType) {
        writeProperty("syncAccountType", syncAccountType);
    }
    public String getSyncAccountType() {
        return (String)readProperty("syncAccountType");
    }

    public void setSyncDirty(Integer syncDirty) {
        writeProperty("syncDirty", syncDirty);
    }
    public Integer getSyncDirty() {
        return (Integer)readProperty("syncDirty");
    }

    public void setSyncEvents(Integer syncEvents) {
        writeProperty("syncEvents", syncEvents);
    }
    public Integer getSyncEvents() {
        return (Integer)readProperty("syncEvents");
    }

    public void setSyncId(String syncId) {
        writeProperty("syncId", syncId);
    }
    public String getSyncId() {
        return (String)readProperty("syncId");
    }

    public void setSyncLocalId(Integer syncLocalId) {
        writeProperty("syncLocalId", syncLocalId);
    }
    public Integer getSyncLocalId() {
        return (Integer)readProperty("syncLocalId");
    }

    public void setSyncMark(Integer syncMark) {
        writeProperty("syncMark", syncMark);
    }
    public Integer getSyncMark() {
        return (Integer)readProperty("syncMark");
    }

    public void setSyncSource(Integer syncSource) {
        writeProperty("syncSource", syncSource);
    }
    public Integer getSyncSource() {
        return (Integer)readProperty("syncSource");
    }

    public void setSyncTime(String syncTime) {
        writeProperty("syncTime", syncTime);
    }
    public String getSyncTime() {
        return (String)readProperty("syncTime");
    }

    public void setSyncVersion(String syncVersion) {
        writeProperty("syncVersion", syncVersion);
    }
    public String getSyncVersion() {
        return (String)readProperty("syncVersion");
    }

    public void setTimezone(String timezone) {
        writeProperty("timezone", timezone);
    }
    public String getTimezone() {
        return (String)readProperty("timezone");
    }

    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }

    public void addToUntitledRel(Events obj) {
        addToManyTarget("untitledRel", obj, true);
    }
    public void removeFromUntitledRel(Events obj) {
        removeToManyTarget("untitledRel", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Events> getUntitledRel() {
        return (List<Events>)readProperty("untitledRel");
    }


}
