package com.android.forge.calendar.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Attendees;
import com.android.forge.calendar.CalendarAlerts;
import com.android.forge.calendar.CalendarSmsAlerts;
import com.android.forge.calendar.Calendars;
import com.android.forge.calendar.EventsRawTimes;
import com.android.forge.calendar.ExtendedProperties;
import com.android.forge.calendar.Instances;
import com.android.forge.calendar.Reminders;

/**
 * Class _Events was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Events extends CayenneDataObject {

    public static final String ALL_DAY_PROPERTY = "allDay";
    public static final String COMMENTS_URI_PROPERTY = "commentsUri";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DTEND_PROPERTY = "dtend";
    public static final String DTEND2_PROPERTY = "dtend2";
    public static final String DTSTART_PROPERTY = "dtstart";
    public static final String DTSTART2_PROPERTY = "dtstart2";
    public static final String DURATION_PROPERTY = "duration";
    public static final String EVENT_LOCATION_PROPERTY = "eventLocation";
    public static final String EVENT_STATUS_PROPERTY = "eventStatus";
    public static final String EVENT_TIMEZONE_PROPERTY = "eventTimezone";
    public static final String EVENT_TIMEZONE2_PROPERTY = "eventTimezone2";
    public static final String EXDATE_PROPERTY = "exdate";
    public static final String EXRULE_PROPERTY = "exrule";
    public static final String FACEBOOK_AVATAR_LARGE_PROPERTY = "facebookAvatarLarge";
    public static final String FACEBOOK_AVATAR_LOCAL_PROPERTY = "facebookAvatarLocal";
    public static final String FACEBOOK_AVATAR_SMALL_PROPERTY = "facebookAvatarSmall";
    public static final String FACEBOOK_SOURCE_ID_PROPERTY = "facebookSourceId";
    public static final String FACEBOOK_TYPE_PROPERTY = "facebookType";
    public static final String GUESTS_CAN_INVITE_OTHERS_PROPERTY = "guestsCanInviteOthers";
    public static final String GUESTS_CAN_MODIFY_PROPERTY = "guestsCanModify";
    public static final String GUESTS_CAN_SEE_GUESTS_PROPERTY = "guestsCanSeeGuests";
    public static final String HAS_ALARM_PROPERTY = "hasAlarm";
    public static final String HAS_ATTENDEE_DATA_PROPERTY = "hasAttendeeData";
    public static final String HAS_EXTENDED_PROPERTIES_PROPERTY = "hasExtendedProperties";
    public static final String HTML_URI_PROPERTY = "htmlUri";
    public static final String I_CAL_GUID_PROPERTY = "iCalGUID";
    public static final String IMPORTANCE_PROPERTY = "importance";
    public static final String LAST_DATE_PROPERTY = "lastDate";
    public static final String LAST_UPDATE_TIME_PROPERTY = "lastUpdateTime";
    public static final String MEETING_STATUS_PROPERTY = "meetingStatus";
    public static final String ORGANIZER_PROPERTY = "organizer";
    public static final String ORIGINAL_ALL_DAY_PROPERTY = "originalAllDay";
    public static final String ORIGINAL_EVENT_PROPERTY = "originalEvent";
    public static final String ORIGINAL_INSTANCE_TIME_PROPERTY = "originalInstanceTime";
    public static final String PARENT_ID_PROPERTY = "parentID";
    public static final String RDATE_PROPERTY = "rdate";
    public static final String RRULE_PROPERTY = "rrule";
    public static final String SELF_ATTENDEE_STATUS_PROPERTY = "selfAttendeeStatus";
    public static final String SYNC_ACCOUNT_PROPERTY = "syncAccount";
    public static final String SYNC_ACCOUNT_TYPE_PROPERTY = "syncAccountType";
    public static final String SYNC_ADAPTER_DATA_PROPERTY = "syncAdapterData";
    public static final String SYNC_DIRTY_PROPERTY = "syncDirty";
    public static final String SYNC_ID_PROPERTY = "syncId";
    public static final String SYNC_LOCAL_ID_PROPERTY = "syncLocalId";
    public static final String SYNC_MARK_PROPERTY = "syncMark";
    public static final String SYNC_TIME_PROPERTY = "syncTime";
    public static final String SYNC_VERSION_PROPERTY = "syncVersion";
    public static final String TITLE_PROPERTY = "title";
    public static final String TRANSPARENCY_PROPERTY = "transparency";
    public static final String VISIBILITY_PROPERTY = "visibility";
    public static final String TO_ATTENDEES_PROPERTY = "toAttendees";
    public static final String TO_CALENDAR_ALERTS_PROPERTY = "toCalendarAlerts";
    public static final String TO_CALENDAR_SMS_ALERTS_PROPERTY = "toCalendarSmsAlerts";
    public static final String TO_CALENDARS_PROPERTY = "toCalendars";
    public static final String TO_EVENTS_RAW_TIMES_PROPERTY = "toEventsRawTimes";
    public static final String TO_EXTENDED_PROPERTIES_PROPERTY = "toExtendedProperties";
    public static final String TO_INSTANCES_PROPERTY = "toInstances";
    public static final String TO_REMINDERS_PROPERTY = "toReminders";

    public static final String _ID_PK_COLUMN = "_id";

    public void setAllDay(Integer allDay) {
        writeProperty("allDay", allDay);
    }
    public Integer getAllDay() {
        return (Integer)readProperty("allDay");
    }

    public void setCommentsUri(String commentsUri) {
        writeProperty("commentsUri", commentsUri);
    }
    public String getCommentsUri() {
        return (String)readProperty("commentsUri");
    }

    public void setDeleted(Integer deleted) {
        writeProperty("deleted", deleted);
    }
    public Integer getDeleted() {
        return (Integer)readProperty("deleted");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDtend(Integer dtend) {
        writeProperty("dtend", dtend);
    }
    public Integer getDtend() {
        return (Integer)readProperty("dtend");
    }

    public void setDtend2(Integer dtend2) {
        writeProperty("dtend2", dtend2);
    }
    public Integer getDtend2() {
        return (Integer)readProperty("dtend2");
    }

    public void setDtstart(Integer dtstart) {
        writeProperty("dtstart", dtstart);
    }
    public Integer getDtstart() {
        return (Integer)readProperty("dtstart");
    }

    public void setDtstart2(Integer dtstart2) {
        writeProperty("dtstart2", dtstart2);
    }
    public Integer getDtstart2() {
        return (Integer)readProperty("dtstart2");
    }

    public void setDuration(String duration) {
        writeProperty("duration", duration);
    }
    public String getDuration() {
        return (String)readProperty("duration");
    }

    public void setEventLocation(String eventLocation) {
        writeProperty("eventLocation", eventLocation);
    }
    public String getEventLocation() {
        return (String)readProperty("eventLocation");
    }

    public void setEventStatus(Integer eventStatus) {
        writeProperty("eventStatus", eventStatus);
    }
    public Integer getEventStatus() {
        return (Integer)readProperty("eventStatus");
    }

    public void setEventTimezone(String eventTimezone) {
        writeProperty("eventTimezone", eventTimezone);
    }
    public String getEventTimezone() {
        return (String)readProperty("eventTimezone");
    }

    public void setEventTimezone2(String eventTimezone2) {
        writeProperty("eventTimezone2", eventTimezone2);
    }
    public String getEventTimezone2() {
        return (String)readProperty("eventTimezone2");
    }

    public void setExdate(String exdate) {
        writeProperty("exdate", exdate);
    }
    public String getExdate() {
        return (String)readProperty("exdate");
    }

    public void setExrule(String exrule) {
        writeProperty("exrule", exrule);
    }
    public String getExrule() {
        return (String)readProperty("exrule");
    }

    public void setFacebookAvatarLarge(String facebookAvatarLarge) {
        writeProperty("facebookAvatarLarge", facebookAvatarLarge);
    }
    public String getFacebookAvatarLarge() {
        return (String)readProperty("facebookAvatarLarge");
    }

    public void setFacebookAvatarLocal(String facebookAvatarLocal) {
        writeProperty("facebookAvatarLocal", facebookAvatarLocal);
    }
    public String getFacebookAvatarLocal() {
        return (String)readProperty("facebookAvatarLocal");
    }

    public void setFacebookAvatarSmall(String facebookAvatarSmall) {
        writeProperty("facebookAvatarSmall", facebookAvatarSmall);
    }
    public String getFacebookAvatarSmall() {
        return (String)readProperty("facebookAvatarSmall");
    }

    public void setFacebookSourceId(String facebookSourceId) {
        writeProperty("facebookSourceId", facebookSourceId);
    }
    public String getFacebookSourceId() {
        return (String)readProperty("facebookSourceId");
    }

    public void setFacebookType(String facebookType) {
        writeProperty("facebookType", facebookType);
    }
    public String getFacebookType() {
        return (String)readProperty("facebookType");
    }

    public void setGuestsCanInviteOthers(Integer guestsCanInviteOthers) {
        writeProperty("guestsCanInviteOthers", guestsCanInviteOthers);
    }
    public Integer getGuestsCanInviteOthers() {
        return (Integer)readProperty("guestsCanInviteOthers");
    }

    public void setGuestsCanModify(Integer guestsCanModify) {
        writeProperty("guestsCanModify", guestsCanModify);
    }
    public Integer getGuestsCanModify() {
        return (Integer)readProperty("guestsCanModify");
    }

    public void setGuestsCanSeeGuests(Integer guestsCanSeeGuests) {
        writeProperty("guestsCanSeeGuests", guestsCanSeeGuests);
    }
    public Integer getGuestsCanSeeGuests() {
        return (Integer)readProperty("guestsCanSeeGuests");
    }

    public void setHasAlarm(Integer hasAlarm) {
        writeProperty("hasAlarm", hasAlarm);
    }
    public Integer getHasAlarm() {
        return (Integer)readProperty("hasAlarm");
    }

    public void setHasAttendeeData(Integer hasAttendeeData) {
        writeProperty("hasAttendeeData", hasAttendeeData);
    }
    public Integer getHasAttendeeData() {
        return (Integer)readProperty("hasAttendeeData");
    }

    public void setHasExtendedProperties(Integer hasExtendedProperties) {
        writeProperty("hasExtendedProperties", hasExtendedProperties);
    }
    public Integer getHasExtendedProperties() {
        return (Integer)readProperty("hasExtendedProperties");
    }

    public void setHtmlUri(String htmlUri) {
        writeProperty("htmlUri", htmlUri);
    }
    public String getHtmlUri() {
        return (String)readProperty("htmlUri");
    }

    public void setICalGUID(String iCalGUID) {
        writeProperty("iCalGUID", iCalGUID);
    }
    public String getICalGUID() {
        return (String)readProperty("iCalGUID");
    }

    public void setImportance(Integer importance) {
        writeProperty("importance", importance);
    }
    public Integer getImportance() {
        return (Integer)readProperty("importance");
    }

    public void setLastDate(Integer lastDate) {
        writeProperty("lastDate", lastDate);
    }
    public Integer getLastDate() {
        return (Integer)readProperty("lastDate");
    }

    public void setLastUpdateTime(String lastUpdateTime) {
        writeProperty("lastUpdateTime", lastUpdateTime);
    }
    public String getLastUpdateTime() {
        return (String)readProperty("lastUpdateTime");
    }

    public void setMeetingStatus(Integer meetingStatus) {
        writeProperty("meetingStatus", meetingStatus);
    }
    public Integer getMeetingStatus() {
        return (Integer)readProperty("meetingStatus");
    }

    public void setOrganizer(String organizer) {
        writeProperty("organizer", organizer);
    }
    public String getOrganizer() {
        return (String)readProperty("organizer");
    }

    public void setOriginalAllDay(Integer originalAllDay) {
        writeProperty("originalAllDay", originalAllDay);
    }
    public Integer getOriginalAllDay() {
        return (Integer)readProperty("originalAllDay");
    }

    public void setOriginalEvent(String originalEvent) {
        writeProperty("originalEvent", originalEvent);
    }
    public String getOriginalEvent() {
        return (String)readProperty("originalEvent");
    }

    public void setOriginalInstanceTime(Integer originalInstanceTime) {
        writeProperty("originalInstanceTime", originalInstanceTime);
    }
    public Integer getOriginalInstanceTime() {
        return (Integer)readProperty("originalInstanceTime");
    }

    public void setParentID(Integer parentID) {
        writeProperty("parentID", parentID);
    }
    public Integer getParentID() {
        return (Integer)readProperty("parentID");
    }

    public void setRdate(String rdate) {
        writeProperty("rdate", rdate);
    }
    public String getRdate() {
        return (String)readProperty("rdate");
    }

    public void setRrule(String rrule) {
        writeProperty("rrule", rrule);
    }
    public String getRrule() {
        return (String)readProperty("rrule");
    }

    public void setSelfAttendeeStatus(Integer selfAttendeeStatus) {
        writeProperty("selfAttendeeStatus", selfAttendeeStatus);
    }
    public Integer getSelfAttendeeStatus() {
        return (Integer)readProperty("selfAttendeeStatus");
    }

    public void setSyncAccount(String syncAccount) {
        writeProperty("syncAccount", syncAccount);
    }
    public String getSyncAccount() {
        return (String)readProperty("syncAccount");
    }

    public void setSyncAccountType(String syncAccountType) {
        writeProperty("syncAccountType", syncAccountType);
    }
    public String getSyncAccountType() {
        return (String)readProperty("syncAccountType");
    }

    public void setSyncAdapterData(String syncAdapterData) {
        writeProperty("syncAdapterData", syncAdapterData);
    }
    public String getSyncAdapterData() {
        return (String)readProperty("syncAdapterData");
    }

    public void setSyncDirty(Integer syncDirty) {
        writeProperty("syncDirty", syncDirty);
    }
    public Integer getSyncDirty() {
        return (Integer)readProperty("syncDirty");
    }

    public void setSyncId(String syncId) {
        writeProperty("syncId", syncId);
    }
    public String getSyncId() {
        return (String)readProperty("syncId");
    }

    public void setSyncLocalId(Integer syncLocalId) {
        writeProperty("syncLocalId", syncLocalId);
    }
    public Integer getSyncLocalId() {
        return (Integer)readProperty("syncLocalId");
    }

    public void setSyncMark(Integer syncMark) {
        writeProperty("syncMark", syncMark);
    }
    public Integer getSyncMark() {
        return (Integer)readProperty("syncMark");
    }

    public void setSyncTime(String syncTime) {
        writeProperty("syncTime", syncTime);
    }
    public String getSyncTime() {
        return (String)readProperty("syncTime");
    }

    public void setSyncVersion(String syncVersion) {
        writeProperty("syncVersion", syncVersion);
    }
    public String getSyncVersion() {
        return (String)readProperty("syncVersion");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setTransparency(Integer transparency) {
        writeProperty("transparency", transparency);
    }
    public Integer getTransparency() {
        return (Integer)readProperty("transparency");
    }

    public void setVisibility(Integer visibility) {
        writeProperty("visibility", visibility);
    }
    public Integer getVisibility() {
        return (Integer)readProperty("visibility");
    }

    public void addToToAttendees(Attendees obj) {
        addToManyTarget("toAttendees", obj, true);
    }
    public void removeFromToAttendees(Attendees obj) {
        removeToManyTarget("toAttendees", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Attendees> getToAttendees() {
        return (List<Attendees>)readProperty("toAttendees");
    }


    public void addToToCalendarAlerts(CalendarAlerts obj) {
        addToManyTarget("toCalendarAlerts", obj, true);
    }
    public void removeFromToCalendarAlerts(CalendarAlerts obj) {
        removeToManyTarget("toCalendarAlerts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CalendarAlerts> getToCalendarAlerts() {
        return (List<CalendarAlerts>)readProperty("toCalendarAlerts");
    }


    public void addToToCalendarSmsAlerts(CalendarSmsAlerts obj) {
        addToManyTarget("toCalendarSmsAlerts", obj, true);
    }
    public void removeFromToCalendarSmsAlerts(CalendarSmsAlerts obj) {
        removeToManyTarget("toCalendarSmsAlerts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CalendarSmsAlerts> getToCalendarSmsAlerts() {
        return (List<CalendarSmsAlerts>)readProperty("toCalendarSmsAlerts");
    }


    public void setToCalendars(Calendars toCalendars) {
        setToOneTarget("toCalendars", toCalendars, true);
    }

    public Calendars getToCalendars() {
        return (Calendars)readProperty("toCalendars");
    }


    public void addToToEventsRawTimes(EventsRawTimes obj) {
        addToManyTarget("toEventsRawTimes", obj, true);
    }
    public void removeFromToEventsRawTimes(EventsRawTimes obj) {
        removeToManyTarget("toEventsRawTimes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EventsRawTimes> getToEventsRawTimes() {
        return (List<EventsRawTimes>)readProperty("toEventsRawTimes");
    }


    public void addToToExtendedProperties(ExtendedProperties obj) {
        addToManyTarget("toExtendedProperties", obj, true);
    }
    public void removeFromToExtendedProperties(ExtendedProperties obj) {
        removeToManyTarget("toExtendedProperties", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ExtendedProperties> getToExtendedProperties() {
        return (List<ExtendedProperties>)readProperty("toExtendedProperties");
    }


    public void addToToInstances(Instances obj) {
        addToManyTarget("toInstances", obj, true);
    }
    public void removeFromToInstances(Instances obj) {
        removeToManyTarget("toInstances", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Instances> getToInstances() {
        return (List<Instances>)readProperty("toInstances");
    }


    public void addToToReminders(Reminders obj) {
        addToManyTarget("toReminders", obj, true);
    }
    public void removeFromToReminders(Reminders obj) {
        removeToManyTarget("toReminders", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Reminders> getToReminders() {
        return (List<Reminders>)readProperty("toReminders");
    }


}
