package com.android.forge.calendar.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _EventsRawTimes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EventsRawTimes extends CayenneDataObject {

    public static final String DTEND2445_PROPERTY = "dtend2445";
    public static final String DTSTART2445_PROPERTY = "dtstart2445";
    public static final String LAST_DATE2445_PROPERTY = "lastDate2445";
    public static final String ORIGINAL_INSTANCE_TIME2445_PROPERTY = "originalInstanceTime2445";
    public static final String TO_EVENTS_PROPERTY = "toEvents";

    public static final String _ID_PK_COLUMN = "_id";

    public void setDtend2445(String dtend2445) {
        writeProperty("dtend2445", dtend2445);
    }
    public String getDtend2445() {
        return (String)readProperty("dtend2445");
    }

    public void setDtstart2445(String dtstart2445) {
        writeProperty("dtstart2445", dtstart2445);
    }
    public String getDtstart2445() {
        return (String)readProperty("dtstart2445");
    }

    public void setLastDate2445(String lastDate2445) {
        writeProperty("lastDate2445", lastDate2445);
    }
    public String getLastDate2445() {
        return (String)readProperty("lastDate2445");
    }

    public void setOriginalInstanceTime2445(String originalInstanceTime2445) {
        writeProperty("originalInstanceTime2445", originalInstanceTime2445);
    }
    public String getOriginalInstanceTime2445() {
        return (String)readProperty("originalInstanceTime2445");
    }

    public void setToEvents(Events toEvents) {
        setToOneTarget("toEvents", toEvents, true);
    }

    public Events getToEvents() {
        return (Events)readProperty("toEvents");
    }


}
