package com.android.forge.calendar.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _ExtendedProperties was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExtendedProperties extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String VALUE_PROPERTY = "value";
    public static final String TO_EVENTS_PROPERTY = "toEvents";

    public static final String _ID_PK_COLUMN = "_id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

    public void setToEvents(Events toEvents) {
        setToOneTarget("toEvents", toEvents, true);
    }

    public Events getToEvents() {
        return (Events)readProperty("toEvents");
    }


}
