package com.android.forge.calendar.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _Instances was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Instances extends CayenneDataObject {

    public static final String BEGIN_PROPERTY = "begin";
    public static final String END_PROPERTY = "end";
    public static final String END_DAY_PROPERTY = "endDay";
    public static final String END_MINUTE_PROPERTY = "endMinute";
    public static final String START_DAY_PROPERTY = "startDay";
    public static final String START_MINUTE_PROPERTY = "startMinute";
    public static final String TO_EVENTS_PROPERTY = "toEvents";

    public static final String _ID_PK_COLUMN = "_id";

    public void setBegin(Integer begin) {
        writeProperty("begin", begin);
    }
    public Integer getBegin() {
        return (Integer)readProperty("begin");
    }

    public void setEnd(Integer end) {
        writeProperty("end", end);
    }
    public Integer getEnd() {
        return (Integer)readProperty("end");
    }

    public void setEndDay(Integer endDay) {
        writeProperty("endDay", endDay);
    }
    public Integer getEndDay() {
        return (Integer)readProperty("endDay");
    }

    public void setEndMinute(Integer endMinute) {
        writeProperty("endMinute", endMinute);
    }
    public Integer getEndMinute() {
        return (Integer)readProperty("endMinute");
    }

    public void setStartDay(Integer startDay) {
        writeProperty("startDay", startDay);
    }
    public Integer getStartDay() {
        return (Integer)readProperty("startDay");
    }

    public void setStartMinute(Integer startMinute) {
        writeProperty("startMinute", startMinute);
    }
    public Integer getStartMinute() {
        return (Integer)readProperty("startMinute");
    }

    public void setToEvents(Events toEvents) {
        setToOneTarget("toEvents", toEvents, true);
    }

    public Events getToEvents() {
        return (Events)readProperty("toEvents");
    }


}
