package com.android.forge.calendar.auto;

import org.apache.cayenne.CayenneDataObject;

import com.android.forge.calendar.Events;

/**
 * Class _Reminders was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Reminders extends CayenneDataObject {

    public static final String METHOD_PROPERTY = "method";
    public static final String MINUTES_PROPERTY = "minutes";
    public static final String TO_EVENTS_PROPERTY = "toEvents";

    public static final String _ID_PK_COLUMN = "_id";

    public void setMethod(Integer method) {
        writeProperty("method", method);
    }
    public Integer getMethod() {
        return (Integer)readProperty("method");
    }

    public void setMinutes(Integer minutes) {
        writeProperty("minutes", minutes);
    }
    public Integer getMinutes() {
        return (Integer)readProperty("minutes");
    }

    public void setToEvents(Events toEvents) {
        setToOneTarget("toEvents", toEvents, true);
    }

    public Events getToEvents() {
        return (Events)readProperty("toEvents");
    }


}
