package com.android.forge.randomnames.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Fakenames was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Fakenames extends CayenneDataObject {

    public static final String BIRTHDAY_PROPERTY = "birthday";
    public static final String CITY_PROPERTY = "city";
    public static final String COMPANY_PROPERTY = "company";
    public static final String EMAILADDRESS_PROPERTY = "emailaddress";
    public static final String GIVENNAME_PROPERTY = "givenname";
    public static final String ID_PROPERTY = "id";
    public static final String STATE_PROPERTY = "state";
    public static final String STREETADDRESS_PROPERTY = "streetaddress";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String TELEPHONENUMBER_PROPERTY = "telephonenumber";
    public static final String ZIPCODE_PROPERTY = "zipcode";

    public static final String ID_PK_COLUMN = "ID";

    public void setBirthday(String birthday) {
        writeProperty("birthday", birthday);
    }
    public String getBirthday() {
        return (String)readProperty("birthday");
    }

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCompany(String company) {
        writeProperty("company", company);
    }
    public String getCompany() {
        return (String)readProperty("company");
    }

    public void setEmailaddress(String emailaddress) {
        writeProperty("emailaddress", emailaddress);
    }
    public String getEmailaddress() {
        return (String)readProperty("emailaddress");
    }

    public void setGivenname(String givenname) {
        writeProperty("givenname", givenname);
    }
    public String getGivenname() {
        return (String)readProperty("givenname");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setStreetaddress(String streetaddress) {
        writeProperty("streetaddress", streetaddress);
    }
    public String getStreetaddress() {
        return (String)readProperty("streetaddress");
    }

    public void setSurname(String surname) {
        writeProperty("surname", surname);
    }
    public String getSurname() {
        return (String)readProperty("surname");
    }

    public void setTelephonenumber(String telephonenumber) {
        writeProperty("telephonenumber", telephonenumber);
    }
    public String getTelephonenumber() {
        return (String)readProperty("telephonenumber");
    }

    public void setZipcode(String zipcode) {
        writeProperty("zipcode", zipcode);
    }
    public String getZipcode() {
        return (String)readProperty("zipcode");
    }

}
